version: '3.8'

services:
  frontend:
    build:
      context: ./frontend    
    ports:
      - "5000:5000"          

  backend:
    build:
      context: ./backend     
    ports:
      - "8080:8080"        
    depends_on:
      - frontend

