version: '3.8'

services:
  frontend:
    build:
      context: ./frontend    
    ports:
      - "5000:5000"            
    environment:
      - REDIS_HOST=redis     

  backend:
    build:
      context: ./backend    
    ports:
      - "8080:8080"                    
    environment:
      - REDIS_HOST=redis
      - POSTGRES_HOST=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=postgres
    container_name: backend

  db:
    image: postgres:13.2-alpine
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: db
    volumes:
      - ./database:/var/lib/postgresql/data

  redis:
    image: redis

  
  
  
  



